name: Build & Release to AKS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:
    
env:
  DOCKER_REPOSITORY: hgacr912.azurecr.io
  IMAGE_TAG: ${{ github.run_number }}
  IMAGE_NAME: webapp

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag webapp:$IMAGE_TAG
      
    - name: Tag the Docker image
      run: docker tag webapp:$IMAGE_TAG $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
      
    - uses: azure/login@v1
      with:
        creds: '{"clientId":"ac0ca313-ae1c-44e8-b71a-28a76df2401f","clientSecret":"XIU8Q~GMwisQP2MgYtXQLWplQnnUsg5~yjk_ubMP","subscriptionId":"cb56ce60-e634-4951-8ac8-ec94c671d4e8","tenantId":"16b3c013-d300-468d-ac64-7eda0820b6d3"}'
        # creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az aks list -o table
      
    - name: Login to Docker Hub
      run: |
        az acr login -n $DOCKER_REPOSITORY --expose-token
        # docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
        
    - name: Push Image to Docker Hub
      run:
        az acr build --registry hgacr912 --image hgmicrosvc:v3 .
        # docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
        
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Resource Group Name
        resource-group: rg-learninglab
        # AKS Cluster Name
        cluster-name: hg-poc-aks

    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1.3
      with:
        # Choose the target Kubernetes namespace. If the namespace is not provided, the commands will run in the default namespace.
        namespace: default
        # Path to the manifest files which will be used for deployment.
        manifests: |
          02_kubernetes_aks/namespace.yaml
          02_kubernetes_aks/app-deploy.yaml
